// Package benchgen generates deterministic synthetic Stylus sources for
// benchmarks. The output uses only features supported by both go-styl and
// reference Stylus (variables, mixins, nesting, arithmetic, color builtins),
// so the same sheet can be timed on either compiler.
package benchgen

import (
	"fmt"
	"strings"
)

// header declares the shared variables and a mixin every sheet uses.
const header = `// synthetic benchmark sheet (generated by internal/benchgen)
base = #3a7bd5
accent = #e91e63
gutter = 8px

btn(bg)
  background bg
  color #fff
  border-radius 4px
  padding gutter (gutter * 2)
  &:hover
    background darken(bg, 10%)

`

// Sheet returns a synthetic stylesheet with n component blocks. Each block is
// a nested rule exercising arithmetic, color functions, and (every fourth
// block) a mixin call; ~190 source bytes per block.
func Sheet(n int) string {
	var b strings.Builder
	b.WriteString(header)
	for i := range n {
		fmt.Fprintf(&b, `.comp-%d
  color lighten(base, %d)
  border 1px solid darken(accent, %d%%)
  margin (gutter * %d) auto
  .title
    font-size 12px + %dpx
    font-weight 600
  &:focus
    outline 2px solid accent
`, i, i%40, i%25, i%4+1, i%6)
		if i%4 == 0 {
			fmt.Fprintf(&b, "  .action\n    btn(lighten(accent, %d))\n", i%30)
		}
		b.WriteByte('\n')
	}
	return b.String()
}
