package styl

import (
	"fmt"
	"go/format"
	"strconv"
	"strings"
	"unicode"

	"github.com/rohanthewiz/go-styl/internal/eval"
	"github.com/rohanthewiz/go-styl/internal/parser"
	"github.com/rohanthewiz/serr"
)

// Var is one root-level Stylus variable and its final compile-time CSS value
// (after Globals seeding and any sheet reassignment).
type Var struct {
	Name  string // Stylus variable name, e.g. "primary"
	Value string // rendered CSS value, e.g. "#0af" or "1px solid red"
}

// Manifest is what a stylesheet exposes to Go code: every class name, element
// ID, and @keyframes animation name that appears in the rendered CSS, plus the
// root-scope variables with their final values. Name lists are sorted and
// duplicate-free, and Vars is sorted by name, so output derived from a
// Manifest is stable across compiles.
//
// Extract/ExtractFile produce one; Manifest.GoSource renders it as a Go
// constants file for typo-proof selector references (see the styl gen
// subcommand for the go:generate wiring).
type Manifest struct {
	// Source is the input path recorded in generated-file headers
	// (set by ExtractFile; "" when extracted from a string).
	Source    string
	Classes   []string
	IDs       []string
	Keyframes []string
	Vars      []Var
	// Scoped maps local class and keyframes names to their scoped forms when
	// the manifest comes from Component; nil otherwise. GoSource then emits
	// the scoped name as each constant's value, still naming the constant
	// after the local name (Card = "card_k3xqa2mf").
	Scoped map[string]string
}

// Extract evaluates Stylus source and returns its Manifest instead of CSS.
// Options is honored the same way as Compile (Globals, IncludePaths, FS, ...),
// so the manifest reflects exactly what a compile with the same options emits.
func Extract(src string, opts Options) (*Manifest, error) {
	sb, err := opts.sandbox(len(src))
	if err != nil {
		return nil, compileErr(err, opts.Filename)
	}
	sheet, err := parser.Parse(src)
	if err != nil {
		return nil, compileErr(err, opts.Filename)
	}
	em, err := eval.ExtractManifest(sheet, eval.Options{
		Pretty:           true,
		MergeDuplicates:  opts.MergeDuplicates,
		Filename:         opts.Filename,
		BaseDir:          opts.baseDir(),
		IncludePaths:     opts.IncludePaths,
		FS:               opts.FS,
		Globals:          opts.Globals,
		CustomProperties: opts.CustomProperties,
		Sandbox:          sb,
	})
	if err != nil {
		return nil, compileErr(err, opts.Filename)
	}
	return manifestFrom(em), nil
}

// manifestFrom converts the evaluator's manifest to the public type.
func manifestFrom(em *eval.Manifest) *Manifest {
	m := &Manifest{
		Classes:   em.Classes,
		IDs:       em.IDs,
		Keyframes: em.Keyframes,
	}
	for _, v := range em.Vars {
		m.Vars = append(m.Vars, Var(v))
	}
	return m
}

// ExtractFile extracts the Manifest of the Stylus file at path (from
// Options.FS when set). The path is recorded as Manifest.Source.
func ExtractFile(path string, opts Options) (*Manifest, error) {
	data, err := readSource(path, opts)
	if err != nil {
		return nil, err
	}
	if opts.Filename == "" {
		opts.Filename = path
	}
	m, err := Extract(string(data), opts)
	if err != nil {
		return nil, err
	}
	m.Source = path
	return m, nil
}

// GoSource renders the manifest as a gofmt-formatted Go source file declaring
// one string constant per name, for compile-checked selector references
// (b.Div("class", css.Card) instead of b.Div("class", "crad")). pkg is the
// package name; "" defaults to "css".
//
// CSS names become exported Go identifiers by splitting on non-alphanumeric
// runes and title-casing the segments ("card__title--big" -> CardTitleBig); a
// leading digit gets an "N" prefix. Classes use the bare identifier; IDs,
// keyframes names, and variables get ID/Anim/Var suffixes so the four groups
// cannot shadow each other. Two names mapping to the same identifier is an
// error naming both.
//
// For a scoped manifest (Scoped set, from Component), classes and keyframes
// names that were renamed hold the scoped name, with the local name as a
// trailing comment.
func (m *Manifest) GoSource(pkg string) ([]byte, error) {
	if pkg == "" {
		pkg = "css"
	}
	if !validGoIdent(pkg) {
		return nil, serr.F("styl gen: %q is not a valid Go package name", pkg)
	}

	var b strings.Builder
	from := ""
	if m.Source != "" {
		from = " from " + m.Source
	}
	fmt.Fprintf(&b, "// Code generated by styl gen%s; DO NOT EDIT.\n\n", from)
	fmt.Fprintf(&b, "// Package %s holds identifiers extracted%s: class names, element IDs,\n", pkg, from)
	b.WriteString("// keyframes animation names, and variable values.\n")
	fmt.Fprintf(&b, "package %s\n", pkg)

	seen := map[string]string{} // Go identifier -> "kind \"css-name\"" that claimed it
	// scopedValues returns the constant values for a class/keyframes group:
	// nil (value = name) for an unscoped manifest, else each name's scoped
	// form, falling back to the name itself for :global-only classes.
	scopedValues := func(names []string) []string {
		if m.Scoped == nil {
			return nil
		}
		vals := make([]string, len(names))
		for i, n := range names {
			if s, ok := m.Scoped[n]; ok {
				vals[i] = s
			} else {
				vals[i] = n
			}
		}
		return vals
	}
	writeGroup := func(comment, kind, suffix string, names []string, values []string) error {
		if len(names) == 0 {
			return nil
		}
		fmt.Fprintf(&b, "\n// %s\nconst (\n", comment)
		for i, name := range names {
			ident, err := goName(name)
			if err != nil {
				return err
			}
			ident += suffix
			desc := fmt.Sprintf("%s %q", kind, name)
			if prev, ok := seen[ident]; ok {
				return serr.F("styl gen: %s and %s both map to Go constant %s", prev, desc, ident)
			}
			seen[ident] = desc
			// The trailing comment names the source identifier whenever the
			// constant's value is something else (a variable's value, a
			// scoped class); a :global class in a scoped manifest keeps its
			// own name and needs none.
			val, note := name, ""
			if values != nil && values[i] != name {
				val, note = values[i], " // "+name
			}
			fmt.Fprintf(&b, "\t%s = %s%s\n", ident, strconv.Quote(val), note)
		}
		b.WriteString(")\n")
		return nil
	}

	varNames := make([]string, len(m.Vars))
	varValues := make([]string, len(m.Vars))
	for i, v := range m.Vars {
		varNames[i], varValues[i] = v.Name, v.Value
	}
	if err := writeGroup("Class names.", "class", "", m.Classes, scopedValues(m.Classes)); err != nil {
		return nil, err
	}
	if err := writeGroup("Element IDs (suffix ID).", "ID", "ID", m.IDs, nil); err != nil {
		return nil, err
	}
	if err := writeGroup("Keyframes animation names (suffix Anim).", "keyframes name", "Anim", m.Keyframes, scopedValues(m.Keyframes)); err != nil {
		return nil, err
	}
	if err := writeGroup("Variable values at compile time (suffix Var).", "variable", "Var", varNames, varValues); err != nil {
		return nil, err
	}

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, serr.Wrap(err, "styl gen: formatting generated source")
	}
	return src, nil
}

// goName converts a CSS name to an exported Go identifier: split on
// non-alphanumeric runes, upper-case each segment's first rune, join
// ("card__title--big" -> CardTitleBig). A leading digit is prefixed with "N"
// ("3col" -> N3col).
func goName(css string) (string, error) {
	var b strings.Builder
	startSegment := true
	for _, r := range css {
		switch {
		case unicode.IsLetter(r):
			if startSegment {
				r = unicode.ToUpper(r)
				startSegment = false
			}
			b.WriteRune(r)
		case unicode.IsDigit(r):
			if b.Len() == 0 {
				b.WriteString("N")
			}
			b.WriteRune(r)
			startSegment = false
		default:
			startSegment = true
		}
	}
	if b.Len() == 0 {
		return "", serr.F("styl gen: name %q has no characters usable in a Go identifier", css)
	}
	return b.String(), nil
}

// validGoIdent reports whether s is usable as a Go package name.
func validGoIdent(s string) bool {
	for i, r := range s {
		switch {
		case unicode.IsLetter(r) || r == '_':
		case unicode.IsDigit(r) && i > 0:
		default:
			return false
		}
	}
	return s != ""
}
